config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  post '/homes/guest_sign_in', to: 'homes#new_guest'
  devise_for :users
  resources :users, only: %i[index show edit update]
  resources :posts do
    resource :favorites, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end

  resources :places do
    resources :reviews, only: %i[index new create edit update destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/place.rb
class Place < ApplicationRecord
  attachment :image

  belongs_to :user
  has_many :posts
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :introduction, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true

  def reviewed_by?(user)
    reviews.where(user_id: user.id).exists?
  end
end

app/models/post.rb
class Post < ApplicationRecord
  attachment :image

  belongs_to :user
  belongs_to :place, optional: true
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true

  # 引数で渡されたユーザidがFavoritesテーブル内に存在（exists?）するかどうかを調べる
  # 存在していればtrue、存在していなければfalseを返す
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :place

  validates :title, presence: true
  validates :body, presence: true
end

app/models/second_place.rb
class SecondPlace < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :image

  has_many :posts, dependent: :destroy
  has_many :places
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy

  # 文字数制限
  validates :email, presence: true
  validates :name, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    # リクエストフォーマット確認用の
    # binding.pry
    @post = Post.find(params[:post_id])
    @comments = @post.comments
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = @post.id
    @comment.save
    # # 非同期通信のため削除
    # redirect_to post_path(post)
  end

  def destroy
    Comment.find_by(id: params[:id], post_id: params[:post_id]).destroy
    @post = Post.find(params[:post_id])
    @comments = @post.comments
    # 非同期通信のため削除
    # redirect_to post_path(params[:post_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top; end

  # ゲストログイン作成用
  def new_guest
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'ゲストユーザー'
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :find, only: %i[show edit update destroy]

  def index
    @places = Place.all
    
  end

  def show
    @user = @place.user
  end

  def new
    @place = Place.new

  end

  def create
    @place = Place.new(place_params)
    @place.user_id = current_user.id
    if @place.save
      redirect_to places_path
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def edit; end

  def update
    @place.update(place_params)
    redirect_to place_path(@place)
  end

  def destroy
    @place.destroy
    redirect_to places_path
  end

  private

  # before_actionで設定
  def find
    @place = Place.find(params[:id])
  end

  # ストロングパラメーター
  def place_params
    params.require(:place).permit(:name, :postal_code, :address, :introduction, :image,)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :login_check, only: [:show, :new, :edit, :update, :destroy]
  before_action :find, only: [:show, :edit, :update, :destroy]
  

  def index
    @posts = Post.all.page(params[:page]).per(9)
  end

  def show
    @comment = Comment.new
    @comments = @post.comments
    @user = @post.user
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @places = Place.all
    if @post.save
      redirect_to posts_path
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def edit; end

  def update
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  # before_actionで設定
  def login_check
    unless user_signed_in?
      flash[:alert] = "ログインしてください"
      redirect_to user_session_path
    end
  end

  def find
    @post = Post.find(params[:id])
  end

  # ストロングパラメーター
  def post_params
    params.require(:post).permit(:title, :body, :image, :place_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find, only: %i[show edit update destroy]

  def index
    @place = Place.find(params[:place_id])
    user = current_user
    @review = user.reviews.find_by(params[:id])
  end

  def new
    @review = current_user.reviews.new
    @place = Place.find(params[:place_id])
  end

  def create
    @review = current_user.reviews.new(review_params)
    @review.place_id = params[:place_id]
    @review.save
    place = @review.place
    redirect_to place_path(place)
  end

  def edit
    @place = @review.place
  end

  def update
    @review.save(review_params)
    place = @review.place
    redirect_to place_path(place)
  end

  def destroy
    @review.destroy
    place = @review.place
    redirect_to place_path(place)
  end

  private

  def find
    @review = Review.find(params[:id])
  end

  # ストロングパラメーター
  def review_params
    params.require(:review).permit(:title, :body, :rate, :place_id, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find, only: %i[show edit update]

  def index
    @users = User.all
  end

  def show; end

  def edit; end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  # before_actionで設定
  def find
    @user = User.find(params[:id])
  end

  # ストロングパラメーター
  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pleces_helper.rb
module PlecesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/second_places_helper.rb
module SecondPlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with(model:[post, comment], data: {remote: true} ) do |f| %>
  <%= f.text_area :body, rows:'5', class: "",placeholder: "コメントを入力" %>
  <%= f.submit "コメント", class: "btn btn-outline-primary p-submit" %>
<% end %>

app/views/comments/_index.html.erb
<% comments.each do |comment| %>
  <% unless comment.id.nil? %>
    <% if comment.user == current_user %>
      <!--チャット風吹き出し-->
      <!--右寄せ-->
      <div class="right flex">
        <div class="">
          <div class="balloon1-right">
            <%= comment.body %>
            <% if comment.user == current_user %>
              <%= link_to post_comment_path(comment.post_id, comment.id), method: :delete, remote: true do %>
                <i class="fa fa-trash" aria-hidden="true"></i>
              <% end %>
            <% end %>
          </div>
          <div class="post-s-u-comment-datetime migi">
            <%= comment.created_at.strftime('%Y/%m/%d') %>
          </div>
        </div>
        <div>
          <%= link_to user_path(comment.user.id) do %>
            <%= attachment_image_tag comment.user, :image, fallback: 'noimage.png', class: 'postcard-user-image', format: 'jpg'  %>
          <% end %>
        </div>
      </div>
    <% else %>
      <!--チャット風吹き出し-->
      <!--左寄せ-->
      <div class="left flex">
        <div>
          <%= link_to user_path(comment.user) do %>
            <div class="image">
              <%= attachment_image_tag comment.user, :image, fallback: 'noimage.png', class: 'postcard-user-image', format: 'jpg'  %>
            </div>
          <% end %>
        </div>
        <div>
          <div class="postcard-user-name"><%= comment.user.name %></div>
          <div class="balloon2-left">
            <%= comment.body %>
            <% if comment.user == current_user %>
              <%= link_to post_comment_path(comment.post_id, comment.id), method: :delete, remote: true do %>
                <i class="fa fa-trash" aria-hidden="true"></i>
              <% end %>
            <% end %>
          </div>  
          <div class="post-s-u-comment-datetime">
            <%= comment.created_at.strftime('%Y/%m/%d') %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/comments/create.js.erb
<!--$('.comment_create').append("%= comment.body %>");-->
<!--$('.js-form')[0].reset(); // 追加-->
$(".comment").html("<%= j(render 'comments/index', post: @post, comments: @comments ) %>");
$("textarea").val('');

app/views/comments/destroy.js.erb
$(".comment").html("<%= j(render 'comments/index', post: @post, comments: @comments ) %>");

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { post: @post }) %>");
$("textarea").val('');

app/views/posts/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-6 offset-3">
      <div class="head post-new">
      <div class="">
        <%= form_with model: @post, local:true do |f| %>
          
            <%= f.file_field :image, class: 'img_field', style: 'display:none;'%>
            <%= attachment_image_tag @post, :image, fallback: 'noimage.png', onClick: "$('.img_field').click()", class: 'center-block img-thumbnail img-responsive img_prev'  %>
          <h4 class="title post-e-title">
            タイトル
          </h4>
          <%= f.text_field :title, placeholder: 'タイトルを入力してください', class: 'post-e-form' %>
          <h4 class="title post-e-title">
            本文
          </h4>
          <%= f.text_area :body, placeholder: '本文を入力してください', class: 'post-e-form', rows: '5'  %>
        　<!--場所選択-->
          <h4 class="title post-e-title">
            結婚式場
          </h4>
          <%= f.collection_select :place_id, Place.all, :id, :name, include_blank: "結婚式場を選択してください" %>
          
          <div class="flex">
            <div>
              <%= f.submit '保存', class: "btn btn-outline-primary p-submit" %>
            </div>
            <div class="post-e-btn">
              <%= link_to '削除', post_path(@post), method: :delete, class: "btn btn-outline-primary p-submit backbtn"%>
            </div>
          </div>
          
        <% end %>
        
      </div>
    
    </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-8 offset-2">
      <div class="head post">
        <%= link_to '投稿する', new_post_path, class: 'btn btn-outline-primary btn-design cut-padding fa fa-pencil' %>
      </div>
      <!--投稿-->
    <div class="row post-wedding">
      <% @posts.each do |post| %>
      <div class="card postcard-wrapper">
        <!---->
        <div class="postcard">
          <%= link_to post_path(post) do %>
          <!--画像-->
            <div>
              <%= attachment_image_tag post, :image, size: "60%", class: 'img-fluid img-size, mx-auto postcard-image' %>
            </div>
            <!--タイトル-->
            <h5 class="postcard-title"><%= post.title %></h5>
            <!--本文-->
            <div class="postcard-text">
              <%= post.body %>
              <div class="reaction">
                <!--いいね-->
                <div class="favorite">
                  <% if user_signed_in? %>
                    <% if post.favorited_by?(current_user) %>
                      <i class="fa fa-heart favorite-color" aria-hidden="true", style=""></i>
                      <span class="postcard-reaction-text favorite-color">
                        <%= post.favorites.count %>
                      </span>
                    <% else %>
                      <i class="fa fa-heart-o postcard-favorite-heart favorite-color" aria-hidden="true"></i>
                      <span class="postcard-reaction-text favorite-color">
                        <%= post.favorites.count %>
                      </span>
                    <% end %>
                  <% else %>
                    <i class="fa fa-heart-o postcard-favorite-heart favorite-color" aria-hidden="true"></i>
                    <span class="postcard-reaction-text favorite-color">
                      <%= post.favorites.count %>
                    </span>
                  <% end %>
                </div>
                <!--コメント-->
                <div class="postcard-comment">
                  <i class="fa fa-commenting comment-color" aria-hidden="true"></i>
                  <span class="postcard-reaction-text comment-color"><%= post.comments.count %></span>
                </div>
              </div>
            </div>
            <!--post.user-->
            <%= link_to user_path(post) do %>
              <div class="postcard-user">
                <!--post.user.img-->
                <%= attachment_image_tag post.user, :image, fallback: "noimage.png", class: 'postcard-user-image' %>
                <!--post.user.name-->
                <span class="postcard-user-name">
                  <%= post.user.name %>
                </span>
              </div>
            <% end %>
            <!--結婚式場情報-->
            <div class="postcard-place-wrapper">
              <h5>
                  使用した結婚式場
              </h5>
              <%= link_to place_path(post.place) do %>
              <div class="flex">
                <div>
                  <%= attachment_image_tag post.place, :image, fallback: 'noimage,png', class: 'postcard-place' %>
                </div>
                <div class="place-name">
                  <p><%= post.place.name %></p>
                  <div>
                    <i class="fa fa-map-marker" aria-hidden="true"></i>
                    <%= post.place.postal_code %>
                    <%= post.place.address %>
                  </div>
                </div>
                </div>
                </div>
              <% end %>
              
            
            <!--結婚式場情報ここまで-->
          <% end %>
        </div>
      </div>
      <% end %>
      <!--postcard終わり-->
    </div>
    <%= paginate @posts %>
    <div></div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-6 offset-3">
      <div class="head post-new">
      <div class="">
        <%= form_with model: @post, local:true do |f| %>
          <%= f.file_field :image, class: 'img_field', style: 'display:none;'%>
          <%= attachment_image_tag @post, :image, fallback: 'noimage.png', onClick: "$('.img_field').click()", class: 'center-block img-thumbnail img-responsive img_prev'  %>
          <h4 class="title post-e-title">
            タイトル
          </h4>
          <%= f.text_field :title, placeholder: 'タイトルを入力してください', class: 'post-e-form' %>
          <h4 class="title post-e-title">
            本文
          </h4>
          <%= f.text_area :body, placeholder: '本文を入力してください', class: 'post-e-form', rows: '5'  %>
        　<!--場所選択-->
          <h4 class="title post-e-title">
            結婚式場
          </h4>
          <%= f.collection_select :place_id, Place.all, :id, :name, include_blank: "結婚式場を選択してください" %>
          <div>
            <%= f.submit '保存', class: "btn btn-outline-primary p-submit backbtn" %>
          </div>
          
        <% end %>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-6 offset-3">
      <div class=" head post-show-wrapper">
        <div class="post-s-post-wrapper">
          <%= attachment_image_tag @post, :image, fallback: "noimage.png" %>
          <h4 class="title post-title">
            <%= @post.title %>
          </h4>
          <!--ユーザー情報-->
          <div class="post-s-user flex">
            <%= attachment_image_tag @post.user, :image, fallback: "noimage.png", class:'postcard-user-image' %>
            <div class="post-s-u-status">
              <p class="post-s-u-name"><%= @post.user.name %></p>
              <p class="post-s-u-date"><%= @post.created_at.strftime('%Y/%m/%d') %></p>
            </div>
          </div>
          <div class="post-s-u-comment-text">
            <%= @post.body %>
          </div>
        </div>
        
        <% if @post.user == current_user %>
          <%= link_to edit_post_path(@post), class:"btn btn-outline-primary p-submit" do %>
            編集<i class="fa fa-pencil-square-o" aria-hidden="true"></i>
          <% end %>
          <%= link_to  post_path(@post), method: :delete, class:"btn btn-outline-primary p-submit" do %>
            削除<i class="fa fa-trash" aria-hidden="true"></i>
          <% end %>
        <% end %>
        <div class="flex post-s-u-favorite">
              <!--いいね-->
          <div class="favorite">
            <%= render 'favorites/favorite', post: @post %>
          </div>
        <!--コメント-->
          <div class="">
            <i class="fa fa-commenting comment-color" aria-hidden="true"></i>
            <span class="postcard-reaction-text comment-color"><%= @post.comments.count %></span>
          </div>
         
          <div class="post-s-user">
            <%= link_to user_path(@post) do %>
              
            <% end %>
          </div>
        </div>
        <!--コメント一覧-->
        <div class="post-s-comment-wrapper">
          <div class="comment post-s-u-comment-wrapper">
            <%= render 'comments/index', post: @post, comments: @comments %>
          </div>
        <!--コメントフォーム-->
          <div class="post-s-u-comment-form">
            <%= render 'comments/form', post: @post, comment: @comment %>
          </div>
        </div>
        
        <!--結婚式場情報ここから-->
        <div class="post-s-u-place-wrapper">
        <h6>式場はこちら</h6>
          <div class="post-s-u-place card">
            <%= link_to place_path(@post.place) do %>
              <div class="flex">
                <!--画像-->
                <div>
                  <%= attachment_image_tag @post.place, :image, fallback: 'noimage,png', class: 'place-img' %>
                </div>
                <div class="text">
                  <!--名前-->
                  <div class="name">
                    <%= @post.place.name %>
                  </div>
                  <!--星-->
                  <div class="star" id="star-rate-<%= @post.place.id %>">
                    <script>
                      $('#star-rate-<%= @post.place.id %>').raty({
                        size: 36,
                        starOff:  '<%= asset_path('star-off.png') %>',
                        starOn : '<%= asset_path('star-on.png') %>',
                        starHalf: '<%= asset_path('star-half.png') %>',
                        half: true,
                        readOnly: true,
                        score: "<%= @post.place.reviews.average(:rate).to_f.round(1) %>",
                      });
                    </script> 
                  </div>
                  <!--住所-->
                  <div class="access">
                    <i class="fa fa-map-marker" aria-hidden="true"></i>
                    <%= @post.place.postal_code %>
                    <%= @post.place.address %>
                  </div>
                  <div class="introduction">
                    <%= @post.place.introduction %>
                  </div>
                  
                </div>
                
              </div>
            <% end %>
            
          </div>
          
            
          
        </div>
          <!--結婚式場情報ここまで-->
        <%= link_to '一覧に戻る', posts_path, class:"btn btn-outline-primary p-submit backbtn" %>
      </div>
    </div>
 </div> 
  