config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  post '/homes/guest_sign_in', to: 'homes#new_guest'
  devise_for :users
  resources :users, only: %i[index show edit update]
  resources :posts do
    resource :favorites, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end

  resources :places do
    resources :reviews, only: %i[index new create edit update destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/place.rb
class Place < ApplicationRecord
  attachment :image

  belongs_to :user
  has_many :posts
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :introduction, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true

  def reviewed_by?(user)
    reviews.where(user_id: user.id).exists?
  end
end

app/models/post.rb
class Post < ApplicationRecord
  attachment :image

  belongs_to :user
  belongs_to :place, optional: true
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true

  # 引数で渡されたユーザidがFavoritesテーブル内に存在（exists?）するかどうかを調べる
  # 存在していればtrue、存在していなければfalseを返す
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :place

  validates :title, presence: true
  validates :body, presence: true
end

app/models/second_place.rb
class SecondPlace < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :image

  has_many :posts, dependent: :destroy
  has_many :places
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy

  # 文字数制限
  validates :email, presence: true
  validates :name, presence: true
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top; end

  # ゲストログイン作成用
  def new_guest
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'ゲストユーザー'
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :find, only: %i[show edit update destroy]

  def index
    @places = Place.all
    
  end

  def show
    @user = @place.user
  end

  def new
    @place = Place.new

  end

  def create
    @place = Place.new(place_params)
    @place.user_id = current_user.id
    if @place.save
      redirect_to places_path
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def edit; end

  def update
    @place.update(place_params)
    redirect_to place_path(@place)
  end

  def destroy
    @place.destroy
    redirect_to places_path
  end

  private

  # before_actionで設定
  def find
    @place = Place.find(params[:id])
  end

  # ストロングパラメーター
  def place_params
    params.require(:place).permit(:name, :postal_code, :address, :introduction, :image,)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :login_check, only: [:show, :new, :edit, :update, :destroy]
  before_action :find, only: [:show, :edit, :update, :destroy]
  

  def index
    @posts = Post.all.page(params[:page]).per(9)
  end

  def show
    @comment = Comment.new
    @comments = @post.comments
    @user = @post.user
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @places = Place.all
    if @post.save
      redirect_to posts_path
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def edit; end

  def update
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  # before_actionで設定
  def login_check
    unless user_signed_in?
      flash[:alert] = "ログインしてください"
      redirect_to user_session_path
    end
  end

  def find
    @post = Post.find(params[:id])
  end

  # ストロングパラメーター
  def post_params
    params.require(:post).permit(:title, :body, :image, :place_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find, only: %i[show edit update destroy]

  def index
    @place = Place.find(params[:place_id])
    user = current_user
    @review = user.reviews.find_by(params[:id])
  end

  def new
    @review = current_user.reviews.new
    @place = Place.find(params[:place_id])
  end

  def create
    @review = current_user.reviews.new(review_params)
    @review.place_id = params[:place_id]
    @review.save
    place = @review.place
    redirect_to place_path(place)
  end

  def edit
    @place = @review.place
  end

  def update
    @review.save(review_params)
    place = @review.place
    redirect_to place_path(place)
  end

  def destroy
    @review.destroy
    place = @review.place
    redirect_to place_path(place)
  end

  private

  def find
    @review = Review.find(params[:id])
  end

  # ストロングパラメーター
  def review_params
    params.require(:review).permit(:title, :body, :rate, :place_id, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find, only: %i[show edit update]

  def index
    @users = User.all
  end

  def show; end

  def edit; end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  # before_actionで設定
  def find
    @user = User.find(params[:id])
  end

  # ストロングパラメーター
  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pleces_helper.rb
module PlecesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/second_places_helper.rb
module SecondPlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
about

app/views/homes/index.html.erb
          <header class="masthead">
            <div class="container d-flex h-100 align-items-center">
                <div class="mx-auto text-center">
                    <h1 class=" mx-auto my-0 text-uppercase">Leave memories</h1>
                    <h2 class="text-white-50 mx-auto mt-2 mb-5"></h2>
                    <% unless signed_in? %>
                    <a><%= link_to 'ログインする', new_user_session_path, class: "btn p-3 px-4 mr-30" %></a>
                    <a><%= link_to 'ゲストログイン（閲覧用）', homes_guest_sign_in_path, method: :post, class: "btn btn-primary-outline p-3 px-4 mr-30" %></a>
                    <% end %>
                </div>
            </div>
        </header>
        <!-- About-->
        <section class="about-section text-center" id="about">
            <div class="container">
                <div class="row">
                    <div class="text-hover col-lg-8 mx-auto">
                        <h2 class="text-white mb-4">SHARE HAPPYとは</h2>
                        <p class="text-contents text-white-50">
                            たくさん笑って、たくさん泣いた大切な思い出を<br>
                            ずっと大切に保管しておくためのサービスです
                        </p>
                    </div>
                </div>
                <!--<img class="img-fluid" src="/img/ipad.png" alt="" />-->
            </div>
        </section>
        <!-- Projects-->
        <section class="projects-section bg-light" id="projects">
            <div class="container">
                <!-- Featured Project Row-->
                <div class="row align-items-center no-gutters mb-4 mb-lg-5">
                    <div class="col-xl-8 col-lg-7"><%= image_tag 'wedding.jpeg', class: 'img-100'%></div>
                    <div class="col-xl-4 col-lg-5">
                        <div class="featured-text text-center text-lg-left">
                            <h4><%= link_to '思い出を残す', posts_path, class:'link' %></h4>
                            <p class="text-black-50 mb-0">思い出を残すだけではなく、<br>次の幸せを作る事ができます。</p>
                        </div>
                    </div>
                </div>
                <!-- Project One Row-->
                <div class="row justify-content-center no-gutters mb-5 mb-lg-0">
                    <div class="col-lg-6"><%= image_tag 'wedding1.jpeg', class: 'img-100'%></div>
                    <div class="col-lg-6">
                        <div class="bg-black text-center h-100 project">
                            <div class="d-flex h-100">
                                <div class="project-text w-100 my-auto text-center text-lg-left">
                                    <h4 class="text-white"><%= link_to '式場を探す', places_path, class:'link_title' %></h4>
                                    <p class="mb-0 text-white-50">レビュー機能、住所検索により<br>より条件に合った式場を検索できます。</p>
                                    <hr class="d-none d-lg-block mb-0 ml-0" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Project Two Row-->
                <div class="row justify-content-center no-gutters">
                    <div class="col-lg-6"><%= image_tag 'wedding2.jpeg', class: 'img-100'%></div>
                    <div class="col-lg-6 order-lg-first">
                        <div class="bg-black text-center h-100 project">
                            <div class="d-flex h-100">
                                <div class="project-text w-100 my-auto text-center text-lg-right">
                                    <h4 class="text-white"><%= link_to '式場を評価する', places_path, class:'link_title' %></h4>
                                    <p class="mb-0 text-white-50">自分が式を挙げた式場の良さを伝えることが出来ます。</p>
                                    <hr class="d-none d-lg-block mb-0 mr-0" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
       
        <footer class="footer bg-black small text-center text-white-50"><div class="container"></div></footer>
      

app/views/places/edit.html.erb
<div class="container">
  <div　class="row">
    <div class="">
      <h1>
      　結婚式場編集
      </h1>
    </div>
    <div class="row">
      <div class="">
        <!--編集したいけど新規作成になっている-->
        <%= form_with model: @place, local:true do |f| %>
        <p>
          <%= f.file_field :image, class: 'img_field', style: 'display:none;'%>
          <%= attachment_image_tag @place, :image, fallback: 'noimage.png', onClick: "$('.img_field').click()", class: 'center-block img-thumbnail img-responsive img_prev'  %>
        </p>
        <p><%= f.text_field :name %></p>
        <p><%= f.text_area :postal_code %></p>
        <p><%= f.text_area :address %></p>
        <p><%= f.text_area :introduction %></p>
        <p><%= f.submit '更新する', class: "btn btn-primary" %></p>
        <p><%= link_to '削除する', place_path(@place), method: :delete, class: "btn btn-primary" %></p>
        <% end %>
        
      </div>
      
      
    </div>
  </div>
</div>

app/views/places/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-6 offset-3">
      <div class="head">
        <%= link_to '式場を追加', new_place_path, class: "btn btn-outline-primary place-in-new" %>
        <% @places.each do |place| %>
          <!--場所情報-->
          <%= link_to place_path(place) do %>
            <div class="place-in-wrapper flex">
              <div class="place-in-flex-left">
                <!--結婚式場画像表示-->
                <%= attachment_image_tag place, :image, fallback: "noimage.png", class: 'place-i-image' %> 
              </div>
              <div class="place-in-flex-right"> 
              <!--結婚式場名表示-->
                <div class="place-in-title title"> 
                  <%= place.name %>
                </div>
                
                <!--結婚式場住所表示-->
                <div class="place-in-address"> 
                <!--こいつが大量発生するから解決する　　-->
                  <i class="fa fa-map-marker" aria-hidden="true"></i>
                  <%= place.address %>
                </div>
                
                <!--レビュー件数-->
                <div class="place-in-review">
                  <div class="flex" id="star-rate-<%= place.id %>">
                    <%= link_to place_path(place) do %>
                      <div class="place-in-r-text">
                        レビュー<%= place.reviews.count %>件 
                      </div>
                    <% end %>
                    <!--星情報-->
                    <script>  
                      $('#star-rate-<%= place.id %>').raty({
                        size     : 24,
                        starOff:  '<%= asset_path('star-off.png') %>',
                        starOn : '<%= asset_path('star-on.png') %>',
                        starHalf: '<%= asset_path('star-half.png') %>',
                        scoreName: 'review[rate]',
                        half: true,
                        readOnly: true,
                        score: "<%= place.reviews.average(:rate).to_f.round(1) %>",
                      });
                    </script> 
                  </div>
                </div>
                
              
                
                <!--結婚式場本文表示-->
                <div class="place-in-text">
                  <%= place.introduction %>
                </div>
                
                <div class="place-in-y-count">
                  <!--何人のユーザーがこの式場を利用したのか表示-->
                  <%= place.posts.count %>人の方が結婚式を開催しました
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
    　</div>
    </div>
  </div>
</div>

app/views/places/new.html.erb
<div class="container">
  <div　class="row">
    <div class="">
      <h1>
      　結婚式場登録
      </h1>
    </div>
    <div class="row">
      <div class="">
        <!--登録フォーム-->
        <!--協会の画像いっぱい保存したい-->
        <%= form_with model: @place, local:true do |f| %>
        <p>
          <%= f.file_field :image, class: 'img_field', style: 'display:none;'%>
          <%= attachment_image_tag @place, :image, fallback: 'noimage.png', onClick: "$('.img_field').click()", class: 'center-block img-thumbnail img-responsive img_prev'  %>
          </p>
        <p><%= f.text_field :name, placeholder: "式場名" %></p>
        <p><%= f.text_area :introduction, placeholder: "紹介文" %></p>
        <p><%= f.text_field :postal_code, placeholder: "郵便番号" %></p>
        <p><%= f.text_field :address, placeholder: "住所" %></p>
        <p><%= f.submit '登録する', class: "btn btn-primary" %></p>
        <%= link_to '戻る', places_path, class: "btn btn-primary", "data-turbolinks": false %>
        <% end %>
        <p></p>
      </div>
      
      
      
    </div>
  </div>
</div>

app/views/places/show.html.erb
 <div class="container-fluid">
  <div class="row">
    <div class="col-6 offset-3">
      <div class="head place-show-wrapper">
        
        <!--結婚式場情報-->
        <div class="place-s-place-wrapper flex">
          <div class="place-s-p-flex-left">
            <h4 class="title placr-s-p-title">
              <%= @place.name %>
              <!--@place作成者なら編集、削除ボタン-->
              <% if @place.user == current_user %>
                <%= link_to edit_place_path(@place) do %>
                  <i class="fa fa-cog btn" aria-hidden="true"></i>
                <% end %>
                <%= link_to place_path(@place), method: :destroy do %>
                  <i class="fa fa-trash btn" aria-hidden="true"></i>
                <% end %>
              <% end %>
            </h4>
            <%= attachment_image_tag @place, :image, size: "100x100", fallback: "noimage.png", class: 'place-s-p-image' %>
          </div>
          <div class="place-s-p-flex-right">
            <div class="flex">
              <div class="place-s-p-review" id="star-rate-<%= @place.id %>"></div>
              <div>
                <script>
                  if ($('#star-rate-<%= @place.id %>').children().length === 0) {
                    $('#star-rate-<%= @place.id %>').raty({
                      size     : 36,
                      starOff:  '<%= asset_path('star-off.png') %>',
                      starOn : '<%= asset_path('star-on.png') %>',
                      starHalf: '<%= asset_path('star-half.png') %>',
                      scoreName: 'review[rate]',
                      half: true,
                      readOnly: true,
                      score: "<%= @place.reviews.average(:rate).to_f.round(1) %>",
                    }); 
                  }
                </script>
                <span><%= @place.reviews.average(:rate) %></span>
                <span>
                  <%= link_to new_place_review_path(@place) do %>
                    <i class="fa fa-pencil-square-o btn btn-outline-primary btn-design" aria-hidden="true"></i>
                  <% end %>
                </span>
              </div>
            </div>
            
            <div class="place-s-p-introduction">
              <%= @place.introduction %>
            </div> 
            <div>
              <span class="place-s-p-postal_code">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <%= @place.postal_code %>
              </span>
              <span class="place-s-p-address">
                <%= @place.address %>
              </span>
            </div>
            
          </div>
        </div>
        <!--結婚式場情報終わり-->
        
        <!--レビュー一覧-->
        <div class="place-s-reviews-wrapper">
          <% @place.reviews.each do |review| %>
          <!--ユーザー情報-->
            <!--レビューを投稿したユーザーが自身ならyoursクラス追加-->
            <% if review.user == current_user %>
              <div class="place-s-review yours">
                <div class="place-s-user">
                  <%= link_to user_path(@user) do %>
                    <%= attachment_image_tag review.user, :image, size: '100x100', format: 'jpg', fallback: "noimage.png", class: 'place-s-r-user-image' %>
                    <span class="place-s-r-user-name">
                      <%= review.user.name %>
                      <%= link_to edit_place_review_path(@place, review) do %>
                      <i class="fa fa-cog btn" aria-hidden="true"></i>
                      <% end %>
                      <%= link_to place_review_path(@place, review), method: :delete do %>
                      <i class="fa fa-trash btn" aria-hidden="true"></i>
                      <% end %>
                    </span>
                  <% end %>
                </div>
                <div class="place-s-r-text">
                  <!--星評価-->
                  <div id="star-rate-<%= review.id %>">
                  <script>
                    $('#star-rate-<%= review.id %>').raty({
                      size: 36,
                      starOff:  '<%= asset_path('star-off.png') %>',
                      starOn : '<%= asset_path('star-on.png') %>',
                      starHalf: '<%= asset_path('star-half.png') %>',
                      half: true,
                      readOnly: true,
                      score: <%= review.rate %>,
                    });
                  </script> 
                  <span class="place-s-r-title"><%= review.title %></span>
                  </div>
                  <!--/星評価-->
                  <div class="place-s-r-datetime"><%= review.created_at.strftime('%Y/%m/%d/%H:%M') %>にレビュー</div>
                  <div class="place-s-r-body"><%= review.body %></div>
                </div>
              </div>
            <% else %>
              <div class="place-s-review">
                <div class="place-s-user">
                  <div>
                    <%= link_to user_path(@user) do %>
                      <%= attachment_image_tag review.user, :image, size: '100x100', format: 'jpg', fallback: "noimage.png", class: 'place-s-r-user-image' %>
                      <span class="place-s-r-user-name"><%= review.user.name %></span>
                    <% end %>
                  </div>
                </div>
                <div class="place-s-r-text">
                  <!--星評価-->
                  <div id="star-rate-<%= review.id %>">
                  <script>
                    $('#star-rate-<%= review.id %>').raty({
                      size: 36,
                      starOff:  '<%= asset_path('star-off.png') %>',
                      starOn : '<%= asset_path('star-on.png') %>',
                      starHalf: '<%= asset_path('star-half.png') %>',
                      half: true,
                      readOnly: true,
                      score: <%= review.rate %>
                    });
                  </script> 
                  <span class="place-s-r-title"><%= review.title %></span>
                  </div>
                  <!--/星評価-->
                  <div class="place-s-r-datetime"><%= review.created_at.strftime('%Y/%m/%d/%H:%M') %>にレビュー</div>
                  <div class="place-s-r-body"><%= review.body %></div>
                </div>
                  
                <!--レビュー削除機能　パス設定まだ-->
                <% if review.user == current_user %>
                  <!--%= link_to "削除", post_comment_path(comment.post, comment), method: :delete, class: "btn btn-danger pull-right" %>-->
                <% end %>
              </div>
            <% end %>
            

          <% end %>
        </div>
        <!--レビュー一覧終わり-->        
        <!--ボタン-->
        <%= link_to '一覧に戻る', places_path, "data-turbolinks": false, class: "btn btn-outline-primary btn-design backbtn" %>
        <% if @place.user == current_user %>
          <%= link_to '編集する', edit_place_path(@place), "data-turbolinks": false, class: "btn btn=outline-primary btn-design" %>
        <% end %>
        <!--ボタン終わり-->      
      </div>
    </div>
  </div>
</div>

      
    

app/views/reviews/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-6 offset-3">
      <div class="head review">
        <div class="r-wrapper">
          <!--タイトル-->
          <h4 class="title">
          この式場をレビュー
          </h4>
          <!--式場-->
          <div class="r-place flex">
            <!--式場画像-->
            <%= attachment_image_tag @place, :image, class: 'image r-p-image' %>
            <div class="r-p-text">
              <!--式場名-->
              <div class="r-p-name"><%= @place.name %></div>
              <!--説明-->
              <div class="r-p-introduction"><%= @place.introduction %></div>
              <!--住所-->
              <span class="r-p-address">
                <i class="fa fa-map-marker" aria-hidden="true"><%= @place.address %></i>
              </span>
            </div>

          </div>
          <!--レビュー-->
          <div class="r-review">
            <%= form_with model: @review, url: place_review_path, local:true do |f| %>
              <!--raty読み込み-->
              <div class="form-group row " id="star">
                <div class>
                  <%= f.label :rate,'評価', class: 'r-p-name' %></br>
                </div>
                  <%= f.hidden_field :rate, id: :review_star %>
              </div>
              <!--星jQuery -->
              <div>
                <script>
                $('#star').raty({
                  size     : 36,
                  starOff:  '<%= asset_path('star-off.png') %>',
                  starOn : '<%= asset_path('star-on.png') %>',
                  starHalf: '<%= asset_path('star-half.png') %>',
                  scoreName: 'review[rate]',
                  half: false,
                });
              </script>  
              </div>
              
              <!--タイトル入力欄-->
              <div class="f-title">
                レビュータイトル
              </div>
              <%= f.text_field :title, placeholder: "最も伝えたいポイントは何ですか？", class: 'r-r-title' %>
              <!--本文入力欄-->
              <div class="f-title">
                レビューを追加
              </div>
              <%= f.text_area :body, placeholder: "良かったところ/気になったところはなんですか？", class: 'r-r-body'%>
              <!--送信ボタン-->
              <%= f.submit "編集", class: "btn btn-lg btn-base-1 mt-20 pull-right", class: 'btn r-r-submit' %>
            <% end %>

          </div>
        </div>  
      </div>
    </div>
  </div>
</div>
 

app/views/reviews/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-4 offset-lg-4 col-md-6 offset-md-3">
      
      <h4>
        レビュ一覧
      </h4>

<p><%= attachment_image_tag @place, :image, size: "100x100", fallback: "noimage.png" %></p>
<p><%= @place.name %></p>
<p><%= @place.postal_code %></p>
<p><%= @place.address %></p>

<!--レビュー作成画面へのリンク 作成してないならnew 作成しているならeditに遷移-->
<% if @place.reviewed_by?(current_user) %>
  <%= link_to 'レビューを編集', edit_place_review_path(@place, @review) %>
<% else %>
  <%= link_to 'レビューを書く', new_place_review_path %>
<% end %>



<!--レビュー一覧を表示-->
<p>
  
</p>
  </div>
  </div>  
</div>

app/views/reviews/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-6 offset-3">
      <div class="head review">
        <div class="r-wrapper">
          <!--タイトル-->
          <h4 class="title">
          この式場をレビュー
          </h4>
          <!--式場-->
          <div class="r-place flex">
            <!--式場画像-->
            <%= attachment_image_tag @place, :image, class: 'image r-p-image' %>
            <div class="r-p-text">
              <!--式場名-->
              <div class="r-p-name"><%= @place.name %></div>
              <!--説明-->
              <div class="r-p-introduction"><%= @place.introduction %></div>
              <!--住所-->
              <span class="r-p-address">
                <i class="fa fa-map-marker" aria-hidden="true"><%= @place.address %></i>
              </span>
            </div>

          </div>
          <!--レビュー-->
          <div class="r-review">
            <%= form_with model: @review, url: place_reviews_path, local:true do |f| %>
              <!--raty読み込み-->
              <div class="form-group row " id="star">
                <div class>
                  <%= f.label :rate,'評価', class: 'r-p-name' %></br>
                </div>
                  <%= f.hidden_field :rate, id: :review_star %>
              </div>
              <!--星jQuery -->
              <div>
                <script>
                $('#star').raty({
                  size     : 36,
                  starOff:  '<%= asset_path('star-off.png') %>',
                  starOn : '<%= asset_path('star-on.png') %>',
                  starHalf: '<%= asset_path('star-half.png') %>',
                  scoreName: 'review[rate]',
                  half: false,
                });
              </script>  
              </div>
              
              <!--タイトル入力欄-->
              <div class="f-title">
                レビュータイトル
              </div>
              <%= f.text_field :title, placeholder: "最も伝えたいポイントは何ですか？", class: 'r-r-title' %>
              <!--本文入力欄-->
              <div class="f-title">
                レビューを追加
              </div>
              <%= f.text_area :body, placeholder: "良かったところ/気になったところはなんですか？", class: 'r-r-body'%>
              <!--送信ボタン-->
              <%= f.submit "送信", class: "btn btn-lg btn-base-1 mt-20 pull-right", class: 'btn r-r-submit' %>
            <% end %>
            <%= link_to '戻る', :back, class: 'btn btn-outline-primary btn-design'%>
          </div>
        </div>  
      </div>
    </div>
  </div>
</div>
 