config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  post '/homes/guest_sign_in', to: 'homes#new_guest'
  devise_for :users
  resources :users, only: %i[index show edit update]
  resources :posts do
    resource :favorites, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end

  resources :places do
    resources :reviews, only: %i[index new create edit update destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/place.rb
class Place < ApplicationRecord
  attachment :image

  belongs_to :user
  has_many :posts
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :introduction, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true

  def reviewed_by?(user)
    reviews.where(user_id: user.id).exists?
  end
end

app/models/post.rb
class Post < ApplicationRecord
  attachment :image

  belongs_to :user
  belongs_to :place, optional: true
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true

  # 引数で渡されたユーザidがFavoritesテーブル内に存在（exists?）するかどうかを調べる
  # 存在していればtrue、存在していなければfalseを返す
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :place

  validates :title, presence: true
  validates :body, presence: true
end

app/models/second_place.rb
class SecondPlace < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :image

  has_many :posts, dependent: :destroy
  has_many :places
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy

  # 文字数制限
  validates :email, presence: true
  validates :name, presence: true
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top; end

  # ゲストログイン作成用
  def new_guest
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'ゲストユーザー'
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :login_check, only: [:show, :new, :edit, :update, :destroy]
  before_action :find, only: [:show, :edit, :update, :destroy]
  

  def index
    @posts = Post.all.page(params[:page]).per(9)
  end

  def show
    @comment = Comment.new
    @comments = @post.comments
    @user = @post.user
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @places = Place.all
    if @post.save
      redirect_to posts_path
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def edit; end

  def update
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  # before_actionで設定
  def login_check
    unless user_signed_in?
      flash[:alert] = "ログインしてください"
      redirect_to user_session_path
    end
  end

  def find
    @post = Post.find(params[:id])
  end

  # ストロングパラメーター
  def post_params
    params.require(:post).permit(:title, :body, :image, :place_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find, only: %i[show edit update]

  def index
    @users = User.all
  end

  def show; end

  def edit; end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  # before_actionで設定
  def find
    @user = User.find(params[:id])
  end

  # ストロングパラメーター
  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pleces_helper.rb
module PlecesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/second_places_helper.rb
module SecondPlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_message.html.erb
<% if content.errors.any? %>
      <h4 class="errors-message">項目が記入されてない箇所があります。</h4>
      <div id ="error_explanation" class="alert alert-danger">
        <ul>
          <% content.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

app/views/layouts/_form.html.erb
<!--検索フォーム-->
      <%= search_form_for search do |f| %>
        <%= f.search_field :name_cont, placeholder: 'キーワード作者名で検索'%>
        <%= f.submit %>
      <% end %>
      
>
<!--<table>-->
<!--  <thead>-->
<!--    <tr>-->
    
<!--    </tr>-->
<!--  </thead>-->
<!--  <tbody>-->
    <!--% users.each do |user| %>-->
      
    <!--% end %>-->
    <!--  <tr>-->
    <!--    <td>%= user.name %></td>-->
    <!--  </tr>-->
    <!--% end %>-->
<!--  </tbody>-->
<!--</table>-->

app/views/layouts/_nav.html.erb
<% if current_page?(root_path) %>
	<nav class="navbar navbar-expand-lg  fixed-top" id="mainNav">
<% else %>
  <nav class="navbar navbar-expand-lg fixed-top navbar-else">
<% end %>
<div class="container">
	<strong><%= link_to 'SHARE HAPPY', root_path, class: 'navbar-brand js-scroll-trigger', 'data-turbolinks': false %></strong>
  <div class="collapse navbar-collapse" id="ftco-nav">
    <ul class="navbar-nav ml-auto">
      <% if signed_in? %>
        <li class="nav-item"><%= link_to "結婚式を見る", posts_path, 'data-turbolinks': false, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to "式場を見る", places_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to "マイページ", user_path(current_user), class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to "サインアウト", destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
			<% else %>
				<li class="nav-item"><%= link_to "結婚式を見る", posts_path, class: 'nav-link' %></a></li>
        <li class="nav-item"><%= link_to "式場を見る", places_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to "ログイン", new_user_session_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to "サインイン", new_user_registration_path, class: 'nav-link' %></a></li>
			<% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SHARE HAPPY</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    

    
    
  </head>

  <body>
    
    <%= render 'layouts/nav' %>
    <%= yield %>
    
  </body>
  <script>
    
  </script>
</html>